spring:
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
