pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "1111"'
            }
        }
       
        stage('Deliver') {
            steps {
                sh 'parent/deliver.sh'
            }
        }
    }
}
